// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsox6FbAH8-osIzLCvvHD2LxvOE4pEGMQ',
    appId: '1:132208920676:web:79aa493dd6900f5d397771',
    messagingSenderId: '132208920676',
    projectId: 'remindus-220fb',
    authDomain: 'remindus-220fb.firebaseapp.com',
    storageBucket: 'remindus-220fb.firebasestorage.app',
    measurementId: 'G-323ETSRCNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC948JXykhywnH1ewURkELjOtq5jifvB0I',
    appId: '1:132208920676:android:7858d96458677255397771',
    messagingSenderId: '132208920676',
    projectId: 'remindus-220fb',
    storageBucket: 'remindus-220fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3avnZizDIJBVhXxdPceCnpKLi3E3AmD0',
    appId: '1:132208920676:ios:7d5e8f24dd488e3f397771',
    messagingSenderId: '132208920676',
    projectId: 'remindus-220fb',
    storageBucket: 'remindus-220fb.firebasestorage.app',
    iosBundleId: 'com.example.remindus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3avnZizDIJBVhXxdPceCnpKLi3E3AmD0',
    appId: '1:132208920676:ios:7d5e8f24dd488e3f397771',
    messagingSenderId: '132208920676',
    projectId: 'remindus-220fb',
    storageBucket: 'remindus-220fb.firebasestorage.app',
    iosBundleId: 'com.example.remindus',
  );
}
